POST http://localhost:5000/register
Content-Type: application/json

 { "name": "John Doe", "email": "john@example.com", "password": "password123", "role": "Normal User" }

###
POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "Subbiah",
    "email": "subba@gmail.com",
    "password": "Owner@123",
    "address": "203 Owner Street",
    "role": "owner"
}

###
POST http://localhost:5000/login
Content-Type: application/json

 { "email": "admin2@example.com", "password": "Admin@123" }

###
GET http://localhost:5000/stores
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQzNTAyMjU0fQ.oZ6XpglDQskE6VaPiujOwsP-JmuXc4FRtl-oZg4Sg8s


###
GET http://localhost:5000/stats
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQzNTAxMTQ2LCJleHAiOjE3NDM1MDQ3NDZ9.1A4hBd-76opXW9S9w9vZyIT_wIZKffWi4AqxRLvvBog

###
POST http://localhost:5000/init-sample-stores
Content-Type: application/json

###
GET http://localhost:5000/stores
Content-Type: application/json